# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

skip_docs
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "BlackCandy.xcodeproj"
    )

    commit_version_bump(
      message: "Bump version to #{get_version_number}.beta#{get_build_number}",
      xcodeproj: "BlackCandy.xcodeproj",
      force: true
    )

    build_app(scheme: "BlackCandy")
    upload_to_testflight

    add_git_tag(tag: "v#{get_version_number}.beta#{get_build_number}")
    push_to_git_remote
  end

  desc "Frame screenshot"
  lane :frame do
    # Clear previous framed screenshots
    sh("find #{ENV['PWD']}/fastlane/screenshots -type f -name '*framed*' -delete")

    frameit(path: "./fastlane/screenshots")
  end
end
