# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    increment_build_number(xcodeproj: "BlackCandy.xcodeproj")
    commit_version_bump(xcodeproj: "BlackCandy.xcodeproj")

    add_git_tag
    push_to_git_remote

    build_app(scheme: "BlackCandy")

    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges"
    )
    upload_to_testflight
  end
end
